/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;
import javax.swing.JComponent;

/**
 *
 * @author mirna
 */
public class frmInicial extends javax.swing.JInternalFrame {

    //defino dos métodosdentro del JInternalFrame y lo instanciamos de la siguiente manera.
    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension DimensionBarra = null;
    //A continuación creamos una función dentro del mismo JInternalFrame como el ejemplo siguiente:
    public void QuitarLaBarraTitulo()
    {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        DimensionBarra = Barra.getPreferredSize();
        Barra.setSize(0,0);
        Barra.setPreferredSize(new Dimension(0,0));
        repaint();
    }
    public frmInicial() {
        initComponents();
        this.setBorder(null);
        QuitarLaBarraTitulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenido = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        pnlBloque1 = new javax.swing.JPanel();
        lblBloque2 = new javax.swing.JLabel();
        pnlBloque2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnlBloque3 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblNombreCambio = new javax.swing.JLabel();
        lblApellidoCambio = new javax.swing.JLabel();
        lblCargoCambio = new javax.swing.JLabel();
        lblEdadCambio = new javax.swing.JLabel();
        lblCodigoCambio = new javax.swing.JLabel();
        lblBloque3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(231, 231, 231));
        setBorder(null);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        lblBienvenido.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(102, 102, 102));
        lblBienvenido.setText("BIENVENIDO");

        lblUsuario.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(102, 102, 102));
        lblUsuario.setText("USUARIO");

        lblReloj.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        lblReloj.setForeground(new java.awt.Color(102, 102, 102));
        lblReloj.setText("12:00 P.M");

        pnlBloque1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnlBloque1Layout = new javax.swing.GroupLayout(pnlBloque1);
        pnlBloque1.setLayout(pnlBloque1Layout);
        pnlBloque1Layout.setHorizontalGroup(
            pnlBloque1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBloque1Layout.setVerticalGroup(
            pnlBloque1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        lblBloque2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblBloque2.setForeground(new java.awt.Color(102, 102, 102));
        lblBloque2.setText("BLOQUE");

        pnlBloque2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnlBloque2Layout = new javax.swing.GroupLayout(pnlBloque2);
        pnlBloque2.setLayout(pnlBloque2Layout);
        pnlBloque2Layout.setHorizontalGroup(
            pnlBloque2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBloque2Layout.setVerticalGroup(
            pnlBloque2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );

        pnlBloque3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnlBloque3Layout = new javax.swing.GroupLayout(pnlBloque3);
        pnlBloque3.setLayout(pnlBloque3Layout);
        pnlBloque3Layout.setHorizontalGroup(
            pnlBloque3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        pnlBloque3Layout.setVerticalGroup(
            pnlBloque3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(51, 51, 51));
        lblNombre.setText("Nombre :");

        lblApellido.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(51, 51, 51));
        lblApellido.setText("Apellido :");

        lblCargo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(51, 51, 51));
        lblCargo.setText("Cargo :");

        lblEdad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(51, 51, 51));
        lblEdad.setText("Edad :");

        lblCodigo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(51, 51, 51));
        lblCodigo.setText("Codigo :");

        lblNombreCambio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNombreCambio.setForeground(new java.awt.Color(153, 153, 153));
        lblNombreCambio.setText("nombre");

        lblApellidoCambio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblApellidoCambio.setForeground(new java.awt.Color(153, 153, 153));
        lblApellidoCambio.setText("apellido");

        lblCargoCambio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCargoCambio.setForeground(new java.awt.Color(153, 153, 153));
        lblCargoCambio.setText("cargo");

        lblEdadCambio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEdadCambio.setForeground(new java.awt.Color(153, 153, 153));
        lblEdadCambio.setText("00");

        lblCodigoCambio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCodigoCambio.setForeground(new java.awt.Color(153, 153, 153));
        lblCodigoCambio.setText("#0000000000000000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlBloque3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido)
                    .addComponent(lblCargo)
                    .addComponent(lblEdad)
                    .addComponent(lblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCambio)
                    .addComponent(lblApellidoCambio)
                    .addComponent(lblCargoCambio)
                    .addComponent(lblEdadCambio)
                    .addComponent(lblCodigoCambio))
                .addGap(0, 89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBloque3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombreCambio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblApellidoCambio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCargoCambio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEdadCambio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(lblCodigoCambio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEdad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCodigo)))
                .addContainerGap())
        );

        lblBloque3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblBloque3.setForeground(new java.awt.Color(102, 102, 102));
        lblBloque3.setText("BLOQUE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlBloque2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBloque2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlBloque1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBloque3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBienvenido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsuario)
                        .addGap(176, 176, 176)
                        .addComponent(lblReloj)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblUsuario)
                    .addComponent(lblBienvenido)
                    .addComponent(lblReloj))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBloque2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlBloque2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBloque3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlBloque1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        this.setBorder(null);
        QuitarLaBarraTitulo();
    }//GEN-LAST:event_formFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblApellidoCambio;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblBloque2;
    private javax.swing.JLabel lblBloque3;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCargoCambio;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoCambio;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEdadCambio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreCambio;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlBloque1;
    private javax.swing.JPanel pnlBloque2;
    private javax.swing.JPanel pnlBloque3;
    // End of variables declaration//GEN-END:variables
}
