/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;

/**
 *
 * @author mirna
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbliniciarSeccion = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        lblRecuperarContraseña = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblBotonConocerMas = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lbliniciarSeccion.setBackground(new java.awt.Color(255, 153, 102));
        lbliniciarSeccion.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        lbliniciarSeccion.setForeground(new java.awt.Color(103, 103, 103));
        lbliniciarSeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbliniciarSeccion.setText("Iniciar Seccion");
        lbliniciarSeccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lbliniciarSeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbliniciarSeccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbliniciarSeccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbliniciarSeccionMouseExited(evt);
            }
        });
        jPanel1.add(lbliniciarSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 300, 40));

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar.png"))); // NOI18N
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 5, -1, -1));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 5, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 300, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 300, 20));

        jPasswordField1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("csdcdscdsjncjkdsncjkdsnc");
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 300, -1));

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("example@ejemplo.com");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 310, -1));

        lblRecuperarContraseña.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblRecuperarContraseña.setForeground(new java.awt.Color(102, 102, 102));
        lblRecuperarContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecuperarContraseña.setText("¿Has olvidado tu contraseña?");
        lblRecuperarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRecuperarContraseñaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRecuperarContraseñaMouseExited(evt);
            }
        });
        jPanel1.add(lblRecuperarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Constraseña");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 380, 570));

        lblBotonConocerMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonVerMas.png"))); // NOI18N
        lblBotonConocerMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBotonConocerMasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBotonConocerMasMouseExited(evt);
            }
        });
        getContentPane().add(lblBotonConocerMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoLogin.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void lblBotonConocerMasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonConocerMasMouseEntered
        lblBotonConocerMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonVerMasNegativo.png")));
    }//GEN-LAST:event_lblBotonConocerMasMouseEntered

    private void lblBotonConocerMasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonConocerMasMouseExited
        lblBotonConocerMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonVerMas.png")));
    }//GEN-LAST:event_lblBotonConocerMasMouseExited

    private void lbliniciarSeccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbliniciarSeccionMouseEntered
        lbliniciarSeccion.setForeground(Color.BLACK);
        lbliniciarSeccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0)));
    }//GEN-LAST:event_lbliniciarSeccionMouseEntered

    private void lbliniciarSeccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbliniciarSeccionMouseExited
        lbliniciarSeccion.setForeground(new java.awt.Color(103, 103, 103));
        lbliniciarSeccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

    }//GEN-LAST:event_lbliniciarSeccionMouseExited

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblRecuperarContraseñaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarContraseñaMouseEntered
        lblRecuperarContraseña.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblRecuperarContraseñaMouseEntered

    private void lblRecuperarContraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarContraseñaMouseExited
        lblRecuperarContraseña.setForeground( new java.awt.Color(103, 103, 103));
    }//GEN-LAST:event_lblRecuperarContraseñaMouseExited

    private void lbliniciarSeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbliniciarSeccionMouseClicked
        frmPrimario f = new frmPrimario();
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbliniciarSeccionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBotonConocerMas;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblRecuperarContraseña;
    private javax.swing.JLabel lbliniciarSeccion;
    // End of variables declaration//GEN-END:variables
}
