/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import constructor.constructo_interfaz;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author mirna
 */
public class frmPrimario extends javax.swing.JFrame {    
    
    Color colorTop;
    Color colorleft;
    Color colorBack;
    
    public void cambioDeColor(int r,int b, int g,int opcion){
        switch(opcion){
            case 1:
                pnlTop.setBackground(new java.awt.Color(r, g, b));
                break;
            case 2:
                pnlMenu.setBackground(new java.awt.Color(r, g, b));
                break;
            case 3:
                pnlContenedor.setBackground(new java.awt.Color(r, g, b));
                break;
        }
    }
    
    public frmPrimario() {
        initComponents();
        setLocationRelativeTo(null);
        pnlOpciones.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblMaximizar = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        lblAreas = new javax.swing.JLabel();
        lblPedidos = new javax.swing.JLabel();
        lblInventario = new javax.swing.JLabel();
        lblTareas = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblProductos = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        lblCerrarSeccion = new javax.swing.JLabel();
        lblOpcion = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();
        jDesktopPanel = new javax.swing.JDesktopPane();
        pnlOpciones = new javax.swing.JPanel();
        pnlCambioDeColor = new javax.swing.JPanel();
        pnlSeleccionDeColorTop = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlSeleccionDeColorLeft = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnlSeleccionDeColorBack = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblTerminar = new javax.swing.JLabel();
        rPersonal = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        lblPersonalizar = new javax.swing.JLabel();
        lblCancelar = new javax.swing.JLabel();
        pnlContenedorDeTema = new javax.swing.JPanel();
        lblTema1 = new javax.swing.JLabel();
        lblTema2 = new javax.swing.JLabel();
        lblTema3 = new javax.swing.JLabel();
        lblTema4 = new javax.swing.JLabel();
        lblTema5 = new javax.swing.JLabel();
        rTema1 = new javax.swing.JRadioButton();
        rTema2 = new javax.swing.JRadioButton();
        rTema3 = new javax.swing.JRadioButton();
        rTema4 = new javax.swing.JRadioButton();
        rTema5 = new javax.swing.JRadioButton();
        lblAplicar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);

        pnlTop.setBackground(new java.awt.Color(153, 153, 153));
        pnlTop.setPreferredSize(new java.awt.Dimension(98, 30));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Minimizar.png"))); // NOI18N
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });

        lblMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Maximizar.png"))); // NOI18N

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimizar)
                .addGap(18, 18, 18)
                .addComponent(lblMaximizar)
                .addGap(18, 18, 18)
                .addComponent(lblCerrar)
                .addGap(19, 19, 19))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMinimizar)
                    .addComponent(lblMaximizar)
                    .addComponent(lblCerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.setBackground(new java.awt.Color(146, 154, 171));
        pnlMenu.setPreferredSize(new java.awt.Dimension(167, 553));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenu.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rollpoint.png"))); // NOI18N
        lblMenu.setPreferredSize(new java.awt.Dimension(150, 30));
        pnlMenu.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 11, 150, -1));

        lblAreas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblAreas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Areas.png"))); // NOI18N
        lblAreas.setText("  Areas");
        lblAreas.setPreferredSize(new java.awt.Dimension(150, 30));
        lblAreas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAreasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAreasMouseExited(evt);
            }
        });
        pnlMenu.add(lblAreas, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 107, 150, -1));

        lblPedidos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pedidos.png"))); // NOI18N
        lblPedidos.setText("  Perdidos");
        lblPedidos.setPreferredSize(new java.awt.Dimension(150, 30));
        lblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPedidosMouseExited(evt);
            }
        });
        pnlMenu.add(lblPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 203, 150, -1));

        lblInventario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Inventario.png"))); // NOI18N
        lblInventario.setText("  Inventario");
        lblInventario.setPreferredSize(new java.awt.Dimension(150, 30));
        lblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInventarioMouseExited(evt);
            }
        });
        pnlMenu.add(lblInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 347, 150, -1));

        lblTareas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tarrea.png"))); // NOI18N
        lblTareas.setText("  Tareas");
        lblTareas.setPreferredSize(new java.awt.Dimension(150, 30));
        lblTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTareasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTareasMouseExited(evt);
            }
        });
        pnlMenu.add(lblTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 155, 150, -1));

        lblUsuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Usuario.png"))); // NOI18N
        lblUsuario.setText("  Usuarios");
        lblUsuario.setPreferredSize(new java.awt.Dimension(150, 30));
        lblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseExited(evt);
            }
        });
        pnlMenu.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 251, 150, -1));

        lblProductos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Productos.png"))); // NOI18N
        lblProductos.setText("  Productos");
        lblProductos.setPreferredSize(new java.awt.Dimension(150, 30));
        lblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProductosMouseExited(evt);
            }
        });
        pnlMenu.add(lblProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 299, 150, -1));

        lblInicio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Inicio.png"))); // NOI18N
        lblInicio.setText("  Inicio");
        lblInicio.setPreferredSize(new java.awt.Dimension(150, 30));
        lblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInicioMouseExited(evt);
            }
        });
        pnlMenu.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 59, 150, -1));

        lblCerrarSeccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCerrarSeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar Seccion.png"))); // NOI18N
        lblCerrarSeccion.setText("  Cerrar Sección");
        lblCerrarSeccion.setPreferredSize(new java.awt.Dimension(150, 30));
        lblCerrarSeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarSeccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarSeccionMouseExited(evt);
            }
        });
        pnlMenu.add(lblCerrarSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 150, -1));

        lblOpcion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblOpcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Opciones.png"))); // NOI18N
        lblOpcion.setText("  Opciones ");
        lblOpcion.setPreferredSize(new java.awt.Dimension(150, 30));
        lblOpcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOpcionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOpcionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOpcionMouseExited(evt);
            }
        });
        pnlMenu.add(lblOpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 460, 150, -1));

        pnlContenedor.setBackground(new java.awt.Color(247, 247, 247));
        pnlContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        pnlContenedor.add(jDesktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 550));

        pnlOpciones.setBackground(new java.awt.Color(247, 247, 247));
        pnlOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSeleccionDeColorTop.setBackground(new java.awt.Color(51, 51, 51));
        pnlSeleccionDeColorTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSeleccionDeColorTopMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Click para cambiar de color");

        javax.swing.GroupLayout pnlSeleccionDeColorTopLayout = new javax.swing.GroupLayout(pnlSeleccionDeColorTop);
        pnlSeleccionDeColorTop.setLayout(pnlSeleccionDeColorTopLayout);
        pnlSeleccionDeColorTopLayout.setHorizontalGroup(
            pnlSeleccionDeColorTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSeleccionDeColorTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(255, 255, 255))
        );
        pnlSeleccionDeColorTopLayout.setVerticalGroup(
            pnlSeleccionDeColorTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSeleccionDeColorTopLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pnlSeleccionDeColorLeft.setBackground(new java.awt.Color(153, 153, 153));
        pnlSeleccionDeColorLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSeleccionDeColorLeftMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Click para cambiar \nde color");

        javax.swing.GroupLayout pnlSeleccionDeColorLeftLayout = new javax.swing.GroupLayout(pnlSeleccionDeColorLeft);
        pnlSeleccionDeColorLeft.setLayout(pnlSeleccionDeColorLeftLayout);
        pnlSeleccionDeColorLeftLayout.setHorizontalGroup(
            pnlSeleccionDeColorLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeleccionDeColorLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSeleccionDeColorLeftLayout.setVerticalGroup(
            pnlSeleccionDeColorLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeleccionDeColorLeftLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pnlSeleccionDeColorBack.setBackground(new java.awt.Color(204, 204, 204));
        pnlSeleccionDeColorBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSeleccionDeColorBackMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Click para cambiar de color");

        javax.swing.GroupLayout pnlSeleccionDeColorBackLayout = new javax.swing.GroupLayout(pnlSeleccionDeColorBack);
        pnlSeleccionDeColorBack.setLayout(pnlSeleccionDeColorBackLayout);
        pnlSeleccionDeColorBackLayout.setHorizontalGroup(
            pnlSeleccionDeColorBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSeleccionDeColorBackLayout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(168, 168, 168))
        );
        pnlSeleccionDeColorBackLayout.setVerticalGroup(
            pnlSeleccionDeColorBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeleccionDeColorBackLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTerminar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblTerminar.setText("Terminar");
        lblTerminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTerminarMouseClicked(evt);
            }
        });

        rPersonal.setBackground(new java.awt.Color(204, 204, 204));
        rPersonal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rPersonal.setText(" Opciones Personalizada");
        rPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPersonalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCambioDeColorLayout = new javax.swing.GroupLayout(pnlCambioDeColor);
        pnlCambioDeColor.setLayout(pnlCambioDeColorLayout);
        pnlCambioDeColorLayout.setHorizontalGroup(
            pnlCambioDeColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambioDeColorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCambioDeColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSeleccionDeColorTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCambioDeColorLayout.createSequentialGroup()
                        .addComponent(rPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTerminar))
                    .addGroup(pnlCambioDeColorLayout.createSequentialGroup()
                        .addComponent(pnlSeleccionDeColorLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSeleccionDeColorBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCambioDeColorLayout.setVerticalGroup(
            pnlCambioDeColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambioDeColorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlCambioDeColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTerminar)
                    .addComponent(rPersonal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSeleccionDeColorTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCambioDeColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSeleccionDeColorLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSeleccionDeColorBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlOpciones.add(pnlCambioDeColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 740, 440));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Temas de color");
        pnlOpciones.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        lblPersonalizar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPersonalizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonalizar.setText("Mas opciones..");
        lblPersonalizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblPersonalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPersonalizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPersonalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPersonalizarMouseExited(evt);
            }
        });
        pnlOpciones.add(lblPersonalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 167, 33));

        lblCancelar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelar.setText("Cancelar");
        lblCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelarMouseExited(evt);
            }
        });
        pnlOpciones.add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 502, 95, 37));

        pnlContenedorDeTema.setBackground(new java.awt.Color(204, 204, 204));

        lblTema1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tema1.png"))); // NOI18N

        lblTema2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tema 2.png"))); // NOI18N

        lblTema3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tema 3.png"))); // NOI18N

        lblTema4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tema 4.png"))); // NOI18N

        lblTema5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tema 5.png"))); // NOI18N

        rTema1.setBackground(new java.awt.Color(204, 204, 204));
        rTema1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rTema1.setText(" Tema 1");
        rTema1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTema1ActionPerformed(evt);
            }
        });

        rTema2.setBackground(new java.awt.Color(204, 204, 204));
        rTema2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rTema2.setText(" Tema 2");
        rTema2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTema2ActionPerformed(evt);
            }
        });

        rTema3.setBackground(new java.awt.Color(204, 204, 204));
        rTema3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rTema3.setText(" Tema 3");
        rTema3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTema3ActionPerformed(evt);
            }
        });

        rTema4.setBackground(new java.awt.Color(204, 204, 204));
        rTema4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rTema4.setText(" Tema 4");
        rTema4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTema4ActionPerformed(evt);
            }
        });

        rTema5.setBackground(new java.awt.Color(204, 204, 204));
        rTema5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rTema5.setText(" Tema 5");
        rTema5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTema5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContenedorDeTemaLayout = new javax.swing.GroupLayout(pnlContenedorDeTema);
        pnlContenedorDeTema.setLayout(pnlContenedorDeTemaLayout);
        pnlContenedorDeTemaLayout.setHorizontalGroup(
            pnlContenedorDeTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorDeTemaLayout.createSequentialGroup()
                .addGroup(pnlContenedorDeTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlContenedorDeTemaLayout.createSequentialGroup()
                        .addComponent(lblTema1)
                        .addGap(30, 30, 30)
                        .addComponent(lblTema2)
                        .addGap(38, 38, 38)
                        .addComponent(lblTema3))
                    .addGroup(pnlContenedorDeTemaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(rTema1)
                        .addGap(108, 108, 108)
                        .addComponent(rTema2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rTema3)
                        .addGap(43, 43, 43)))
                .addGroup(pnlContenedorDeTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlContenedorDeTemaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblTema4)
                        .addGap(36, 36, 36)
                        .addComponent(lblTema5)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(pnlContenedorDeTemaLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(rTema4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rTema5)
                        .addGap(43, 43, 43))))
        );
        pnlContenedorDeTemaLayout.setVerticalGroup(
            pnlContenedorDeTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorDeTemaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContenedorDeTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTema1)
                    .addComponent(lblTema2)
                    .addComponent(lblTema3)
                    .addComponent(lblTema4)
                    .addComponent(lblTema5))
                .addGap(18, 18, 18)
                .addGroup(pnlContenedorDeTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rTema2)
                    .addComponent(rTema1)
                    .addComponent(rTema4)
                    .addComponent(rTema5)
                    .addComponent(rTema3))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlOpciones.add(pnlContenedorDeTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, -1, -1));

        lblAplicar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblAplicar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAplicar.setText("Aplicar");
        lblAplicar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblAplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAplicarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAplicarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAplicarMouseExited(evt);
            }
        });
        pnlOpciones.add(lblAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 502, 95, 37));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Selecciona tu tema de preferencia");
        pnlOpciones.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, -1, -1));

        pnlContenedor.add(pnlOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseEntered
        lblInicio.setBorder(javax.swing.BorderFactory.createLineBorder(Color.DARK_GRAY));
    }//GEN-LAST:event_lblInicioMouseEntered

    private void lblInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseExited
        lblInicio.setBorder(null);
    }//GEN-LAST:event_lblInicioMouseExited

    private void lblAreasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAreasMouseEntered
        lblAreas.setBorder(javax.swing.BorderFactory.createLineBorder(Color.DARK_GRAY));
    }//GEN-LAST:event_lblAreasMouseEntered

    private void lblAreasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAreasMouseExited
        lblAreas.setBorder(null);
    }//GEN-LAST:event_lblAreasMouseExited

    private void lblTareasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTareasMouseEntered
        lblTareas.setBorder(javax.swing.BorderFactory.createLineBorder(Color.DARK_GRAY));
    }//GEN-LAST:event_lblTareasMouseEntered

    private void lblTareasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTareasMouseExited
        lblTareas.setBorder(null);
    }//GEN-LAST:event_lblTareasMouseExited

    private void lblPedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedidosMouseEntered
        lblPedidos.setBorder(javax.swing.BorderFactory.createLineBorder(Color.DARK_GRAY));
    }//GEN-LAST:event_lblPedidosMouseEntered

    private void lblPedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedidosMouseExited
        lblPedidos.setBorder(null);
    }//GEN-LAST:event_lblPedidosMouseExited

    private void lblUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseEntered
        lblUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(Color.DARK_GRAY));
    }//GEN-LAST:event_lblUsuarioMouseEntered

    private void lblUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseExited
        lblUsuario.setBorder(null);
    }//GEN-LAST:event_lblUsuarioMouseExited

    private void lblProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMouseEntered
        lblProductos.setBorder(javax.swing.BorderFactory.createLineBorder(Color.DARK_GRAY));
    }//GEN-LAST:event_lblProductosMouseEntered

    private void lblProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMouseExited
        lblProductos.setBorder(null);
    }//GEN-LAST:event_lblProductosMouseExited

    private void lblInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventarioMouseEntered
        lblInventario.setBorder(javax.swing.BorderFactory.createLineBorder(Color.DARK_GRAY));
    }//GEN-LAST:event_lblInventarioMouseEntered

    private void lblInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventarioMouseExited
        lblInventario.setBorder(null);
    }//GEN-LAST:event_lblInventarioMouseExited

    private void lblOpcionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpcionMouseEntered
        lblOpcion.setBorder(javax.swing.BorderFactory.createLineBorder(Color.DARK_GRAY));
    }//GEN-LAST:event_lblOpcionMouseEntered

    private void lblOpcionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpcionMouseExited
        lblOpcion.setBorder(null);
    }//GEN-LAST:event_lblOpcionMouseExited

    private void lblCerrarSeccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSeccionMouseEntered
        lblCerrarSeccion.setBorder(javax.swing.BorderFactory.createLineBorder(Color.DARK_GRAY));
    }//GEN-LAST:event_lblCerrarSeccionMouseEntered

    private void lblCerrarSeccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSeccionMouseExited
        lblCerrarSeccion.setBorder(null);
    }//GEN-LAST:event_lblCerrarSeccionMouseExited

    private void lblOpcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpcionMouseClicked
        jDesktopPanel.setVisible(false);
        pnlOpciones.setVisible(true);
        pnlCambioDeColor.setVisible(false);
    }//GEN-LAST:event_lblOpcionMouseClicked

    private void rTema1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTema1ActionPerformed
        rTema2.setSelected(false);
        rTema3.setSelected(false);
        rTema4.setSelected(false);
        rTema5.setSelected(false);
        rPersonal.setSelected(false);
    }//GEN-LAST:event_rTema1ActionPerformed

    private void lblAplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAplicarMouseClicked
        if (rTema1.isSelected() == true && rTema2.isSelected() == false && rTema3.isSelected() == false && rTema4.isSelected() == false && rTema5.isSelected() == false) {
            cambioDeColor(35,55,77,1);
            cambioDeColor(16,137,255,2);
            cambioDeColor(229,229,229,3);
        }
        else if (rTema1.isSelected() == false && rTema2.isSelected() == true && rTema3.isSelected() == false && rTema4.isSelected() == false && rTema5.isSelected() == false) {
            cambioDeColor(66,0,0,1);
            cambioDeColor(212,215,221,2);
            cambioDeColor(246,246,246,3);
        }
        else if (rTema1.isSelected() == false && rTema2.isSelected() == false && rTema3.isSelected() == true && rTema4.isSelected() == false && rTema5.isSelected() == false) {
            cambioDeColor(34,40,49,1);
            cambioDeColor(50,224,196,2);
            cambioDeColor(57,62,70,3);
        }
        else if (rTema1.isSelected() == false && rTema2.isSelected() == false && rTema3.isSelected() == false && rTema4.isSelected() == true && rTema5.isSelected() == false) {
            cambioDeColor(207,117,0,1);
            cambioDeColor(240,165,0,2);
            cambioDeColor(264,244,244,3);
        }
        else if (rTema1.isSelected() == false && rTema2.isSelected() == false && rTema3.isSelected() == false && rTema4.isSelected() == false && rTema5.isSelected() == true) {
            cambioDeColor(255,115,21,1);
            cambioDeColor(58,53,53,2);
            cambioDeColor(244,244,244,3);
        }
        else if (rPersonal.isSelected() == true){
            colorTop = pnlSeleccionDeColorTop.getBackground();
            colorleft = pnlSeleccionDeColorLeft.getBackground();
            colorBack = pnlSeleccionDeColorBack.getBackground();
            
            pnlTop.setBackground(colorTop);
            pnlMenu.setBackground(colorleft);
            pnlContenedor.setBackground(colorBack);
        }
    }//GEN-LAST:event_lblAplicarMouseClicked

    private void rTema2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTema2ActionPerformed
        rTema1.setSelected(false);
        rTema3.setSelected(false);
        rTema4.setSelected(false);
        rTema5.setSelected(false);
        rPersonal.setSelected(false);
    }//GEN-LAST:event_rTema2ActionPerformed

    private void rTema3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTema3ActionPerformed
        rTema2.setSelected(false);
        rTema1.setSelected(false);
        rTema4.setSelected(false);
        rTema5.setSelected(false);
        rPersonal.setSelected(false);
    }//GEN-LAST:event_rTema3ActionPerformed

    private void rTema4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTema4ActionPerformed
        rTema2.setSelected(false);
        rTema3.setSelected(false);
        rTema1.setSelected(false);
        rTema5.setSelected(false);
        rPersonal.setSelected(false);
    }//GEN-LAST:event_rTema4ActionPerformed

    private void rTema5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTema5ActionPerformed
        rTema2.setSelected(false);
        rTema3.setSelected(false);
        rTema4.setSelected(false);
        rTema1.setSelected(false);
        rPersonal.setSelected(false);
    }//GEN-LAST:event_rTema5ActionPerformed

    private void lblAplicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAplicarMouseEntered
        lblAplicar.setForeground(Color.LIGHT_GRAY);
        lblAplicar.setBorder(new javax.swing.border.LineBorder(Color.LIGHT_GRAY, 1, true));
    }//GEN-LAST:event_lblAplicarMouseEntered

    private void lblAplicarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAplicarMouseExited
        lblAplicar.setForeground(Color.BLACK);
        lblAplicar.setBorder(new javax.swing.border.LineBorder(Color.BLACK, 1, true));
    }//GEN-LAST:event_lblAplicarMouseExited

    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        pnlOpciones.setVisible(false);
        jDesktopPanel.setVisible(true);
    }//GEN-LAST:event_lblCancelarMouseClicked

    private void lblCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseEntered
        lblCancelar.setForeground(Color.LIGHT_GRAY);
        lblCancelar.setBorder(new javax.swing.border.LineBorder(Color.LIGHT_GRAY, 1, true));
    }//GEN-LAST:event_lblCancelarMouseEntered

    private void lblCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseExited
        lblCancelar.setForeground(Color.BLACK);
        lblCancelar.setBorder(new javax.swing.border.LineBorder(Color.BLACK, 1, true));
    }//GEN-LAST:event_lblCancelarMouseExited

    private void lblPersonalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonalizarMouseClicked
        pnlCambioDeColor.setVisible(true);
    }//GEN-LAST:event_lblPersonalizarMouseClicked

    private void lblPersonalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonalizarMouseEntered
        lblPersonalizar.setForeground(Color.LIGHT_GRAY);
        lblPersonalizar.setBorder(new javax.swing.border.LineBorder(Color.LIGHT_GRAY, 1, true));
    }//GEN-LAST:event_lblPersonalizarMouseEntered

    private void lblPersonalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonalizarMouseExited
        lblPersonalizar.setForeground(Color.BLACK);
        lblPersonalizar.setBorder(new javax.swing.border.LineBorder(Color.BLACK, 1, true));
    }//GEN-LAST:event_lblPersonalizarMouseExited

    private void lblTerminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTerminarMouseClicked
        pnlCambioDeColor.setVisible(false);
    }//GEN-LAST:event_lblTerminarMouseClicked

    private void pnlSeleccionDeColorTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSeleccionDeColorTopMouseClicked
        Color colores;
        JColorChooser c = new JColorChooser();
        colores = c.showDialog(this,"Selecciones el color que quieres",Color.BLUE);
        pnlSeleccionDeColorTop.setBackground(colores);
    }//GEN-LAST:event_pnlSeleccionDeColorTopMouseClicked

    private void pnlSeleccionDeColorLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSeleccionDeColorLeftMouseClicked
        Color colores;
        JColorChooser c = new JColorChooser();
        colores = c.showDialog(this,"Selecciones el color que quieres",Color.BLUE);
        pnlSeleccionDeColorLeft.setBackground(colores);
    }//GEN-LAST:event_pnlSeleccionDeColorLeftMouseClicked

    private void pnlSeleccionDeColorBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSeleccionDeColorBackMouseClicked
        Color colores;
        JColorChooser c = new JColorChooser();
        colores = c.showDialog(this,"Selecciones el color que quieres",Color.BLUE);
        pnlSeleccionDeColorBack.setBackground(colores);
    }//GEN-LAST:event_pnlSeleccionDeColorBackMouseClicked

    private void rPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPersonalActionPerformed
        rTema2.setSelected(false);
        rTema3.setSelected(false);
        rTema4.setSelected(false);
        rTema1.setSelected(false);
        rTema5.setSelected(false);
    }//GEN-LAST:event_rPersonalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrimario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrimario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrimario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrimario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrimario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAplicar;
    private javax.swing.JLabel lblAreas;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblCerrarSeccion;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblInventario;
    private javax.swing.JLabel lblMaximizar;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblOpcion;
    private javax.swing.JLabel lblPedidos;
    private javax.swing.JLabel lblPersonalizar;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblTareas;
    private javax.swing.JLabel lblTema1;
    private javax.swing.JLabel lblTema2;
    private javax.swing.JLabel lblTema3;
    private javax.swing.JLabel lblTema4;
    private javax.swing.JLabel lblTema5;
    private javax.swing.JLabel lblTerminar;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlCambioDeColor;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlContenedorDeTema;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlSeleccionDeColorBack;
    private javax.swing.JPanel pnlSeleccionDeColorLeft;
    private javax.swing.JPanel pnlSeleccionDeColorTop;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JRadioButton rPersonal;
    private javax.swing.JRadioButton rTema1;
    private javax.swing.JRadioButton rTema2;
    private javax.swing.JRadioButton rTema3;
    private javax.swing.JRadioButton rTema4;
    private javax.swing.JRadioButton rTema5;
    // End of variables declaration//GEN-END:variables
}
